In [1]:
import pandas as pd
import pandas_profiling
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# Purpose of this Notebook

I wanted to analyze Twitch data and Metacritic data to answer various questions that I have about live-streaming. Are there games that viewers are more likely to watch that contributors are not streaming as much as others? Are there games that have increased or decreased viewership over the years? Does a video gameâ€™s score from a review site influence how popular that game is to watch or stream on Twitch? Based on that review, can we predict if that game will be popular to watch or stream? 

Twitch Game Data is a data set from Ran Kirsh's analysis on Kaggle. Link to this: 
https://www.kaggle.com/datasets/rankirsh/evolution-of-top-games-on-twitch/discussion?select=Twitch_game_data.csv

Metacritic Data is a data set from Deep Contractor's analysis on Kaggle. Link to this: 
https://www.kaggle.com/datasets/deepcontractor/top-video-games-19952021-metacritic

I will have to connect the two data sets by Video Game name.

### Loading Twitch Data

In [2]:
#Twitch Data CSV loaded
Twitch = pd.read_csv('Twitch_16_21.csv', encoding='cp1252')
Twitch.head()

,Rank,Game,Month,Year,Hours_watched,Hours_Streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
0,1,League of Legends,1,2016,94377226,1362044 hours,530270,2903,129172,127021,1833,69.29
1,2,Counter-Strike: Global Offensive,1,2016,47832863,830105 hours,372654,2197,120849,64378,1117,57.62
2,3,Dota 2,1,2016,45185893,433397 hours,315083,1100,44074,60815,583,104.26
3,4,Hearthstone,1,2016,39936159,235903 hours,131357,517,36170,53749,317,169.29
4,5,Call of Duty: Black Ops III,1,2016,16153057,1151578 hours,71639,3620,214054,21740,1549,14.03

### Loading Metacritic Data

In [3]:
#Metacritic Data CSV loaded
Metacritic = pd.read_csv('Metacritic_Vid_Games_95_21.csv')
Metacritic.head()

,Game_Name,Platform,Release_Date,Game_Summary,Meta_Score,User_Review
0,The Legend of Zelda: Ocarina of Time,Nintendo 64,23-Nov-98,"As a young boy, Link is tricked by Ganondorf, ...",99,9.1
1,Tony Hawk's Pro Skater 2,PlayStation,20-Sep-00,As most major publishers' development efforts ...,98,7.4
2,Grand Theft Auto IV,PlayStation 3,29-Apr-08,[Metacritic's 2008 PS3 Game of the Year; Also ...,98,7.7
3,SoulCalibur,Dreamcast,8-Sep-99,"This is a tale of souls and swords, transcendi...",98,8.4
4,Grand Theft Auto IV,Xbox 360,29-Apr-08,[Metacritic's 2008 Xbox 360 Game of the Year; ...,98,7.9